services:
#  db:
#    image: postgres:12
#    ports:
#      - 5432:5432
#    environment:
#      POSTGRES_USER: connector
#      POSTGRES_PASSWORD: password
#      POSTGRES_DB: sourcedb

  clickhouse:
    image: clickhouse/clickhouse-server
    container_name: clickhouse
    ports:
      - "5123:8123"
      - "9123:9000"
    volumes:
      - ./clickhouse:/var/lib/clickhouse
      - ./clickhouse/logs:/var/log/clickhouse-server
    environment:
      - CLICKHOUSE_USER=clickhouse
      - CLICKHOUSE_PASSWORD=clickhouse
      - max_block_size=1000000